// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteApplicationsByAppIdQueriesByQueryIdData, DeleteApplicationsByAppIdQueriesByQueryIdErrors, DeleteApplicationsByAppIdQueriesByQueryIdResponses, DeleteApplicationsByAppIdQueriesByQueryIdStesBySteIdData, DeleteApplicationsByAppIdQueriesByQueryIdStesBySteIdErrors, DeleteApplicationsByAppIdQueriesByQueryIdStesBySteIdResponses, DeleteApplicationsByIdData, DeleteApplicationsByIdErrors, DeleteApplicationsByIdResponses, GetApplicationsByIdData, GetApplicationsByIdErrors, GetApplicationsByIdResponses, GetApplicationsData, GetApplicationsErrors, GetApplicationsResponses, GetContractsBuyerRegionsData, GetContractsBuyerRegionsErrors, GetContractsBuyerRegionsResponses, GetContractsByIdData, GetContractsByIdErrors, GetContractsByIdItemsData, GetContractsByIdItemsErrors, GetContractsByIdItemsResponses, GetContractsByIdResponses, GetContractsData, GetContractsErrors, GetContractsResponses, GetContractsSupplierRegionsData, GetContractsSupplierRegionsErrors, GetContractsSupplierRegionsResponses, GetHealthData, GetHealthResponses, GetSearchItemsData, GetSearchItemsErrors, GetSearchItemsResponses, GetSteByIdData, GetSteByIdErrors, GetSteByIdResponses, GetSteCategoriesData, GetSteCategoriesErrors, GetSteCategoriesResponses, GetSteData, GetSteErrors, GetSteResponses, PostApplicationsByAppIdQueriesByQueryIdStesData, PostApplicationsByAppIdQueriesByQueryIdStesErrors, PostApplicationsByAppIdQueriesByQueryIdStesResponses, PostApplicationsByIdQueriesData, PostApplicationsByIdQueriesErrors, PostApplicationsByIdQueriesResponses, PostApplicationsData, PostApplicationsErrors, PostApplicationsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Health check
 */
export const getHealth = <ThrowOnError extends boolean = false>(options?: Options<GetHealthData, ThrowOnError>) => (options?.client ?? client).get<GetHealthResponses, unknown, ThrowOnError>({ url: '/health', ...options });

/**
 * Список СТЕ с пагинацией и фильтрацией
 */
export const getSte = <ThrowOnError extends boolean = false>(options?: Options<GetSteData, ThrowOnError>) => (options?.client ?? client).get<GetSteResponses, GetSteErrors, ThrowOnError>({ url: '/ste', ...options });

/**
 * Список уникальных категорий СТЕ
 */
export const getSteCategories = <ThrowOnError extends boolean = false>(options?: Options<GetSteCategoriesData, ThrowOnError>) => (options?.client ?? client).get<GetSteCategoriesResponses, GetSteCategoriesErrors, ThrowOnError>({ url: '/ste/categories', ...options });

/**
 * Получить СТЕ по ID
 */
export const getSteById = <ThrowOnError extends boolean = false>(options: Options<GetSteByIdData, ThrowOnError>) => (options.client ?? client).get<GetSteByIdResponses, GetSteByIdErrors, ThrowOnError>({ url: '/ste/{id}', ...options });

/**
 * Список контрактов с пагинацией и фильтрацией
 */
export const getContracts = <ThrowOnError extends boolean = false>(options?: Options<GetContractsData, ThrowOnError>) => (options?.client ?? client).get<GetContractsResponses, GetContractsErrors, ThrowOnError>({ url: '/contracts', ...options });

/**
 * Список уникальных регионов поставщиков
 */
export const getContractsSupplierRegions = <ThrowOnError extends boolean = false>(options?: Options<GetContractsSupplierRegionsData, ThrowOnError>) => (options?.client ?? client).get<GetContractsSupplierRegionsResponses, GetContractsSupplierRegionsErrors, ThrowOnError>({ url: '/contracts/supplier-regions', ...options });

/**
 * Список уникальных регионов заказчиков
 */
export const getContractsBuyerRegions = <ThrowOnError extends boolean = false>(options?: Options<GetContractsBuyerRegionsData, ThrowOnError>) => (options?.client ?? client).get<GetContractsBuyerRegionsResponses, GetContractsBuyerRegionsErrors, ThrowOnError>({ url: '/contracts/buyer-regions', ...options });

/**
 * Контракт по ID с позициями и данными СТЕ
 */
export const getContractsById = <ThrowOnError extends boolean = false>(options: Options<GetContractsByIdData, ThrowOnError>) => (options.client ?? client).get<GetContractsByIdResponses, GetContractsByIdErrors, ThrowOnError>({ url: '/contracts/{id}', ...options });

/**
 * Позиции контракта по ID контракта
 */
export const getContractsByIdItems = <ThrowOnError extends boolean = false>(options: Options<GetContractsByIdItemsData, ThrowOnError>) => (options.client ?? client).get<GetContractsByIdItemsResponses, GetContractsByIdItemsErrors, ThrowOnError>({ url: '/contracts/{id}/items', ...options });

/**
 * Список заявок с пагинацией
 */
export const getApplications = <ThrowOnError extends boolean = false>(options?: Options<GetApplicationsData, ThrowOnError>) => (options?.client ?? client).get<GetApplicationsResponses, GetApplicationsErrors, ThrowOnError>({ url: '/applications', ...options });

/**
 * Создать заявку
 */
export const postApplications = <ThrowOnError extends boolean = false>(options: Options<PostApplicationsData, ThrowOnError>) => (options.client ?? client).post<PostApplicationsResponses, PostApplicationsErrors, ThrowOnError>({
    url: '/applications',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Удалить заявку (каскад)
 */
export const deleteApplicationsById = <ThrowOnError extends boolean = false>(options: Options<DeleteApplicationsByIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteApplicationsByIdResponses, DeleteApplicationsByIdErrors, ThrowOnError>({ url: '/applications/{id}', ...options });

/**
 * Заявка со всеми запросами и привязанными СТЕ
 */
export const getApplicationsById = <ThrowOnError extends boolean = false>(options: Options<GetApplicationsByIdData, ThrowOnError>) => (options.client ?? client).get<GetApplicationsByIdResponses, GetApplicationsByIdErrors, ThrowOnError>({ url: '/applications/{id}', ...options });

/**
 * Добавить запрос в заявку
 */
export const postApplicationsByIdQueries = <ThrowOnError extends boolean = false>(options: Options<PostApplicationsByIdQueriesData, ThrowOnError>) => (options.client ?? client).post<PostApplicationsByIdQueriesResponses, PostApplicationsByIdQueriesErrors, ThrowOnError>({
    url: '/applications/{id}/queries',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Удалить запрос из заявки
 */
export const deleteApplicationsByAppIdQueriesByQueryId = <ThrowOnError extends boolean = false>(options: Options<DeleteApplicationsByAppIdQueriesByQueryIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteApplicationsByAppIdQueriesByQueryIdResponses, DeleteApplicationsByAppIdQueriesByQueryIdErrors, ThrowOnError>({ url: '/applications/{appId}/queries/{queryId}', ...options });

/**
 * Привязать СТЕ к запросу
 */
export const postApplicationsByAppIdQueriesByQueryIdStes = <ThrowOnError extends boolean = false>(options: Options<PostApplicationsByAppIdQueriesByQueryIdStesData, ThrowOnError>) => (options.client ?? client).post<PostApplicationsByAppIdQueriesByQueryIdStesResponses, PostApplicationsByAppIdQueriesByQueryIdStesErrors, ThrowOnError>({
    url: '/applications/{appId}/queries/{queryId}/stes',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Отвязать СТЕ от запроса
 */
export const deleteApplicationsByAppIdQueriesByQueryIdStesBySteId = <ThrowOnError extends boolean = false>(options: Options<DeleteApplicationsByAppIdQueriesByQueryIdStesBySteIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteApplicationsByAppIdQueriesByQueryIdStesBySteIdResponses, DeleteApplicationsByAppIdQueriesByQueryIdStesBySteIdErrors, ThrowOnError>({ url: '/applications/{appId}/queries/{queryId}/stes/{steId}', ...options });

/**
 * Полнотекстовый поиск позиций контрактов по СТЕ
 */
export const getSearchItems = <ThrowOnError extends boolean = false>(options: Options<GetSearchItemsData, ThrowOnError>) => (options.client ?? client).get<GetSearchItemsResponses, GetSearchItemsErrors, ThrowOnError>({ url: '/search/items', ...options });
