// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3000' | (string & {});
};

export type Error = {
    error?: string;
};

export type Ste = {
    id?: number;
    name?: string;
    category?: string | null;
    manufacturer?: string | null;
    /**
     * Формат: Ключ1:Значение1;Ключ2:Значение2;...
     */
    characteristics?: string | null;
};

export type Contract = {
    id?: number;
    procurementName?: string;
    procurementMethod?: string | null;
    /**
     * numeric
     */
    initialContractValue?: string | null;
    /**
     * numeric
     */
    contractValueAfterSigning?: string | null;
    reductionPercent?: string | null;
    vatRate?: string | null;
    contractSigningDate?: string | null;
    buyerInn?: string | null;
    buyerRegion?: string | null;
    supplierInn?: string | null;
    supplierRegion?: string | null;
};

export type ContractItemWithSte = {
    id?: number;
    steId?: number | null;
    steItemName?: string | null;
    quantity?: string | null;
    unit?: string | null;
    unitPrice?: string | null;
    steName?: string | null;
    steCategory?: string | null;
    steManufacturer?: string | null;
    steCharacteristics?: string | null;
};

export type Application = {
    id?: number;
    name?: string;
    createdAt?: string;
};

export type ApplicationQuery = {
    id?: number;
    applicationId?: number;
    queryText?: string;
};

export type ApplicationQuerySte = {
    id?: number;
    queryId?: number;
    steId?: number;
    /**
     * numeric(5,2)
     */
    nameMatchPercent?: string;
};

export type ApplicationQuerySteWithSte = {
    id?: number;
    queryId?: number;
    steId?: number;
    nameMatchPercent?: string;
    steName?: string | null;
    steCategory?: string | null;
    steManufacturer?: string | null;
    steCharacteristics?: string | null;
};

export type ApplicationQueryFull = {
    id?: number;
    applicationId?: number;
    queryText?: string;
    stes?: Array<ApplicationQuerySteWithSte>;
};

export type ApplicationFull = Application & {
    queries?: Array<ApplicationQueryFull>;
};

export type SearchItem = {
    id?: number;
    contract_id?: number;
    ste_id?: number | null;
    ste_item_name?: string | null;
    quantity?: string | null;
    unit?: string | null;
    unit_price?: string | null;
    ste_name?: string | null;
    ste_category?: string | null;
    ste_manufacturer?: string | null;
    ste_characteristics?: string | null;
    /**
     * Релевантность полнотекстового поиска
     */
    rank?: number;
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    /**
     * OK
     */
    200: {
        status?: string;
    };
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type GetSteData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        limit?: number;
        /**
         * Поиск по названию (ilike)
         */
        search?: string;
        /**
         * Фильтр по категории (ilike)
         */
        category?: string;
    };
    url: '/ste';
};

export type GetSteErrors = {
    /**
     * Error
     */
    500: Error;
};

export type GetSteError = GetSteErrors[keyof GetSteErrors];

export type GetSteResponses = {
    /**
     * OK
     */
    200: {
        data?: Array<Ste>;
        total?: number;
        page?: number;
        limit?: number;
    };
};

export type GetSteResponse = GetSteResponses[keyof GetSteResponses];

export type GetSteCategoriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ste/categories';
};

export type GetSteCategoriesErrors = {
    /**
     * Error
     */
    500: Error;
};

export type GetSteCategoriesError = GetSteCategoriesErrors[keyof GetSteCategoriesErrors];

export type GetSteCategoriesResponses = {
    /**
     * OK
     */
    200: Array<string>;
};

export type GetSteCategoriesResponse = GetSteCategoriesResponses[keyof GetSteCategoriesResponses];

export type GetSteByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/ste/{id}';
};

export type GetSteByIdErrors = {
    /**
     * Error
     */
    400: Error;
    /**
     * Error
     */
    404: Error;
    /**
     * Error
     */
    500: Error;
};

export type GetSteByIdError = GetSteByIdErrors[keyof GetSteByIdErrors];

export type GetSteByIdResponses = {
    /**
     * OK
     */
    200: Ste;
};

export type GetSteByIdResponse = GetSteByIdResponses[keyof GetSteByIdResponses];

export type GetContractsData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        limit?: number;
        /**
         * Поиск по наименованию закупки (ilike)
         */
        search?: string;
        /**
         * ИНН заказчика (точное совпадение)
         */
        buyerInn?: string;
        /**
         * ИНН поставщика (точное совпадение)
         */
        supplierInn?: string;
        /**
         * Регион заказчика (ilike)
         */
        region?: string;
        /**
         * Дата заключения от (ISO 8601)
         */
        dateFrom?: string;
        /**
         * Дата заключения до (ISO 8601)
         */
        dateTo?: string;
    };
    url: '/contracts';
};

export type GetContractsErrors = {
    /**
     * Error
     */
    500: Error;
};

export type GetContractsError = GetContractsErrors[keyof GetContractsErrors];

export type GetContractsResponses = {
    /**
     * OK
     */
    200: {
        data?: Array<Contract>;
        total?: number;
        page?: number;
        limit?: number;
    };
};

export type GetContractsResponse = GetContractsResponses[keyof GetContractsResponses];

export type GetContractsSupplierRegionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/contracts/supplier-regions';
};

export type GetContractsSupplierRegionsErrors = {
    /**
     * Error
     */
    500: Error;
};

export type GetContractsSupplierRegionsError = GetContractsSupplierRegionsErrors[keyof GetContractsSupplierRegionsErrors];

export type GetContractsSupplierRegionsResponses = {
    /**
     * OK
     */
    200: Array<string>;
};

export type GetContractsSupplierRegionsResponse = GetContractsSupplierRegionsResponses[keyof GetContractsSupplierRegionsResponses];

export type GetContractsBuyerRegionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/contracts/buyer-regions';
};

export type GetContractsBuyerRegionsErrors = {
    /**
     * Error
     */
    500: Error;
};

export type GetContractsBuyerRegionsError = GetContractsBuyerRegionsErrors[keyof GetContractsBuyerRegionsErrors];

export type GetContractsBuyerRegionsResponses = {
    /**
     * OK
     */
    200: Array<string>;
};

export type GetContractsBuyerRegionsResponse = GetContractsBuyerRegionsResponses[keyof GetContractsBuyerRegionsResponses];

export type GetContractsByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/contracts/{id}';
};

export type GetContractsByIdErrors = {
    /**
     * Error
     */
    400: Error;
    /**
     * Error
     */
    404: Error;
    /**
     * Error
     */
    500: Error;
};

export type GetContractsByIdError = GetContractsByIdErrors[keyof GetContractsByIdErrors];

export type GetContractsByIdResponses = {
    /**
     * OK
     */
    200: Contract & {
        items?: Array<ContractItemWithSte>;
    };
};

export type GetContractsByIdResponse = GetContractsByIdResponses[keyof GetContractsByIdResponses];

export type GetContractsByIdItemsData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/contracts/{id}/items';
};

export type GetContractsByIdItemsErrors = {
    /**
     * Error
     */
    400: Error;
    /**
     * Error
     */
    404: Error;
    /**
     * Error
     */
    500: Error;
};

export type GetContractsByIdItemsError = GetContractsByIdItemsErrors[keyof GetContractsByIdItemsErrors];

export type GetContractsByIdItemsResponses = {
    /**
     * OK
     */
    200: Array<ContractItemWithSte>;
};

export type GetContractsByIdItemsResponse = GetContractsByIdItemsResponses[keyof GetContractsByIdItemsResponses];

export type GetApplicationsData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        limit?: number;
    };
    url: '/applications';
};

export type GetApplicationsErrors = {
    /**
     * Error
     */
    500: Error;
};

export type GetApplicationsError = GetApplicationsErrors[keyof GetApplicationsErrors];

export type GetApplicationsResponses = {
    /**
     * OK
     */
    200: {
        data?: Array<Application>;
        total?: number;
        page?: number;
        limit?: number;
    };
};

export type GetApplicationsResponse = GetApplicationsResponses[keyof GetApplicationsResponses];

export type PostApplicationsData = {
    body: {
        name: string;
        queries?: Array<string>;
    };
    path?: never;
    query?: never;
    url: '/applications';
};

export type PostApplicationsErrors = {
    /**
     * Error
     */
    400: Error;
    /**
     * Error
     */
    500: Error;
};

export type PostApplicationsError = PostApplicationsErrors[keyof PostApplicationsErrors];

export type PostApplicationsResponses = {
    /**
     * Created
     */
    201: Application;
};

export type PostApplicationsResponse = PostApplicationsResponses[keyof PostApplicationsResponses];

export type DeleteApplicationsByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/applications/{id}';
};

export type DeleteApplicationsByIdErrors = {
    /**
     * Error
     */
    400: Error;
    /**
     * Error
     */
    404: Error;
    /**
     * Error
     */
    500: Error;
};

export type DeleteApplicationsByIdError = DeleteApplicationsByIdErrors[keyof DeleteApplicationsByIdErrors];

export type DeleteApplicationsByIdResponses = {
    /**
     * OK
     */
    200: {
        ok?: boolean;
    };
};

export type DeleteApplicationsByIdResponse = DeleteApplicationsByIdResponses[keyof DeleteApplicationsByIdResponses];

export type GetApplicationsByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/applications/{id}';
};

export type GetApplicationsByIdErrors = {
    /**
     * Error
     */
    400: Error;
    /**
     * Error
     */
    404: Error;
    /**
     * Error
     */
    500: Error;
};

export type GetApplicationsByIdError = GetApplicationsByIdErrors[keyof GetApplicationsByIdErrors];

export type GetApplicationsByIdResponses = {
    /**
     * OK
     */
    200: ApplicationFull;
};

export type GetApplicationsByIdResponse = GetApplicationsByIdResponses[keyof GetApplicationsByIdResponses];

export type PostApplicationsByIdQueriesData = {
    body: {
        queryText: string;
    };
    path: {
        id: number;
    };
    query?: never;
    url: '/applications/{id}/queries';
};

export type PostApplicationsByIdQueriesErrors = {
    /**
     * Error
     */
    400: Error;
    /**
     * Error
     */
    404: Error;
    /**
     * Error
     */
    500: Error;
};

export type PostApplicationsByIdQueriesError = PostApplicationsByIdQueriesErrors[keyof PostApplicationsByIdQueriesErrors];

export type PostApplicationsByIdQueriesResponses = {
    /**
     * Created
     */
    201: ApplicationQuery;
};

export type PostApplicationsByIdQueriesResponse = PostApplicationsByIdQueriesResponses[keyof PostApplicationsByIdQueriesResponses];

export type DeleteApplicationsByAppIdQueriesByQueryIdData = {
    body?: never;
    path: {
        appId: number;
        queryId: number;
    };
    query?: never;
    url: '/applications/{appId}/queries/{queryId}';
};

export type DeleteApplicationsByAppIdQueriesByQueryIdErrors = {
    /**
     * Error
     */
    400: Error;
    /**
     * Error
     */
    404: Error;
    /**
     * Error
     */
    500: Error;
};

export type DeleteApplicationsByAppIdQueriesByQueryIdError = DeleteApplicationsByAppIdQueriesByQueryIdErrors[keyof DeleteApplicationsByAppIdQueriesByQueryIdErrors];

export type DeleteApplicationsByAppIdQueriesByQueryIdResponses = {
    /**
     * OK
     */
    200: {
        ok?: boolean;
    };
};

export type DeleteApplicationsByAppIdQueriesByQueryIdResponse = DeleteApplicationsByAppIdQueriesByQueryIdResponses[keyof DeleteApplicationsByAppIdQueriesByQueryIdResponses];

export type PostApplicationsByAppIdQueriesByQueryIdStesData = {
    body: {
        steId: number;
        nameMatchPercent: number;
    };
    path: {
        appId: number;
        queryId: number;
    };
    query?: never;
    url: '/applications/{appId}/queries/{queryId}/stes';
};

export type PostApplicationsByAppIdQueriesByQueryIdStesErrors = {
    /**
     * Error
     */
    400: Error;
    /**
     * Error
     */
    404: Error;
    /**
     * Error
     */
    500: Error;
};

export type PostApplicationsByAppIdQueriesByQueryIdStesError = PostApplicationsByAppIdQueriesByQueryIdStesErrors[keyof PostApplicationsByAppIdQueriesByQueryIdStesErrors];

export type PostApplicationsByAppIdQueriesByQueryIdStesResponses = {
    /**
     * Created
     */
    201: ApplicationQuerySte;
};

export type PostApplicationsByAppIdQueriesByQueryIdStesResponse = PostApplicationsByAppIdQueriesByQueryIdStesResponses[keyof PostApplicationsByAppIdQueriesByQueryIdStesResponses];

export type DeleteApplicationsByAppIdQueriesByQueryIdStesBySteIdData = {
    body?: never;
    path: {
        appId: number;
        queryId: number;
        steId: number;
    };
    query?: never;
    url: '/applications/{appId}/queries/{queryId}/stes/{steId}';
};

export type DeleteApplicationsByAppIdQueriesByQueryIdStesBySteIdErrors = {
    /**
     * Error
     */
    400: Error;
    /**
     * Error
     */
    404: Error;
    /**
     * Error
     */
    500: Error;
};

export type DeleteApplicationsByAppIdQueriesByQueryIdStesBySteIdError = DeleteApplicationsByAppIdQueriesByQueryIdStesBySteIdErrors[keyof DeleteApplicationsByAppIdQueriesByQueryIdStesBySteIdErrors];

export type DeleteApplicationsByAppIdQueriesByQueryIdStesBySteIdResponses = {
    /**
     * OK
     */
    200: {
        ok?: boolean;
    };
};

export type DeleteApplicationsByAppIdQueriesByQueryIdStesBySteIdResponse = DeleteApplicationsByAppIdQueriesByQueryIdStesBySteIdResponses[keyof DeleteApplicationsByAppIdQueriesByQueryIdStesBySteIdResponses];

export type GetSearchItemsData = {
    body?: never;
    path?: never;
    query: {
        page?: number;
        limit?: number;
        /**
         * Поисковый запрос (русский язык)
         */
        q: string;
    };
    url: '/search/items';
};

export type GetSearchItemsErrors = {
    /**
     * Error
     */
    400: Error;
    /**
     * Error
     */
    500: Error;
};

export type GetSearchItemsError = GetSearchItemsErrors[keyof GetSearchItemsErrors];

export type GetSearchItemsResponses = {
    /**
     * OK
     */
    200: {
        data?: Array<SearchItem>;
        total?: number;
        page?: number;
        limit?: number;
    };
};

export type GetSearchItemsResponse = GetSearchItemsResponses[keyof GetSearchItemsResponses];
